### PR TITLE
Add instructions on solving missing DLL issue

### PR DESCRIPTION
**Pull request by Jettford**

### CODE REVIEW

**Comment by averysumner** [comment]
Better solution would be to copy the dlls into the build folder.

**Comment by Jettford** [comment]
That is a good point to be honest.

**Comment by TheMatt2** [comment]
The file can be moved programmatically by adding a line in CMakeLists.txt

```
229     endif(UNIX)
230    if(WIN32)
231    link_directories(${mysql_SOURCE_DIR}/lib64/vs14)
+++    file(COPY ${mysql_SOURCE_DIR}/lib64/mysqlcppconn-9-vs14.dll DESTINATION ${PROJECT_BINARY_DIR})
232    endif(WIN32)
```

**Comment by Jettford** [comment]
You need to also move the lib*.dll's too

**Comment by TheMatt2** [comment]
Interesting. It seemed work anyway.

There is probably a way to use `file(GLOB...)` to move all of them at once, otherwise they would all need to be listed.
Or just list them.

Perhaps there should also be a check to move the `.pdb` files if it is a debug build?

**Comment by Jettford** [comment]
PDBs are referenced by absolute paths, they shouldn't be moved

**Comment by averysumner** [comment]
zlib’s dll should also be moved (which notably is named different is the build is debug. Best solution would probably be to recursively add all .dll or .so files to the build folder.

**Comment by TheMatt2** [comment]
> PDBs are referenced by absolute paths, they shouldn't be moved

I'm a bit confused how this could be the case. Specifically for the PDB files for mysql's connector, they are downloaded from mysql website, not compiled.

So how could they be referenced by absolute path?

I assume they are meant to be in the same folder as the corresponding DLL, though I don't know how to really test this.

**Comment by Jettford** [comment]
Hmm, I have never thought about that. I just know inside the PE files the PDB is always defined by its absolute compile path

**Comment by averysumner** [comment]
> Hmm, I have never thought about that. I just know inside the PE files the PDB is always defined by its absolute compile path

You would likely need to manually re-reference the pdb file if you ever wanted to use it. I don't see it being worth it to move the PDBs by default.

**Comment by Xiphoseer** [comment]
There's a cmake `install` directive + command specifically for moving binaries and libraries where they need to be. Doing that as part of build isn't really the best option IMO

**Comment by Xiphoseer** [comment]
Suggestion: Merge this and open an issue about automatic installation?

**Comment by aronwk-aaron** [comment]
Taking Xipho's suggestion and merging this doc change, then making an issue to fix the cmake issue

**Pull request merged**
