### PR TITLE
chore: Change dServer and related code to use BitStream references

### PR DESCRIPTION
**Pull request by jadebenn**
This is the last of the changes as far as I can tell. I will be testing the combined reference changes in game and will report back on their status.

### CODE REVIEW

**Comment by jadebenn** [comment]
Combined all the bitstream reference branches into one local branch and ran the game for about an hour where I went from AG to NS to GF following the main questline. Seems stable to me.

**Review by aronwk-aaron — APPROVED** [review]

**Comment by EmosewaMC** [comment]
Can you also check the ignore list functionality (add, remove and fetch on world load)?  doesnt sound like that was checked

**Review by EmosewaMC — APPROVED** [review]
pending the above test request

**Comment by jadebenn** [comment]
Yeah, I'll do that when I have time later today.

**Comment by jadebenn** [comment]
tested by blocking an alt, reloading, and seeing they were still blocked

**Pull request merged**
