### PR TITLE
chore: Move Player ghosting functionality to GhostComponent

### PR DESCRIPTION
**Pull request by EmosewaMC**
Waiting on #1412 
Tested that ghosting still works and players are still firing off the OnPlayerLeave and relevant handlers.

### CODE REVIEW

**Review by aronwk-aaron — DISMISSED** [review]

**Review by Wincent01 — CHANGES_REQUESTED** [review]
Change to ghosting vector to a hashset.

**Comment by EmosewaMC** [comment]
> Change to ghosting vector to a hashset.

Are you sure you would like to integrate a change like this into this PR?  I tried to make this one as close to just moving the code as possible and updating the calls where necessary.  Is this still a change you would like?

**Review by Wincent01 — COMMENTED** [review]
Felt like an appropriate time to get that change through; shouldn't have phrased it as a requirement though.

**Comment by EmosewaMC** [comment]
> Felt like an appropriate time to get that change through; shouldn't have phrased it as a requirement though.

will do so then, just wanted to double check since this seemed to be optimized for storage and cache locality for some reason.  Not sure if that was for speed or because unordered_set was unknown about at the time

**Comment by Wincent01** [comment]
This was written before I'd taken the data structures course at uni lol

**Review by Wincent01 — DISMISSED** [review]

**Review by aronwk-aaron — APPROVED** [review]

**Comment by aronwk-aaron** [comment]
>conflict
:(

**Review by aronwk-aaron — APPROVED** [review]

**Comment by EmosewaMC** [comment]
> Change to ghosting vector to a hashset.

I love the prospect of "Please get rid of my old code now, we dont need it anymore"

**Review by Jettford — APPROVED** [review]

**Pull request merged**
