### PR TITLE
ChatServer respawn after crash

### PR DESCRIPTION
**Pull request by cuzitsjonny**
- MasterServer now respawns ChatServer on crash
- WorldServer now attempts to reconnect to ChatServer

### CODE REVIEW

**Comment by IAmVolvic** [comment]
Has this been tested?

**Comment by IAmVolvic** [comment]
> > Has this been tested?
> 
> Yes. Since you seem to be so worried, why don't you back me up by setting up a second test?

Weirdly while trying to figure out the issue with the ChatServer crashing we ended up fixing it by putting it in a try catch ( Wanted to get the root issue )

The crashing happens because of this error 

" ChatServer_1640005560.log:[20-12-21 10:59:04] [ChatServer] Bruh moment: Duplicate entry '1152921508901818643-1152921508901823303' for key 'friends.PRIMARY' "

**Comment by DarwinAnim8or** [comment]
@IAmVolvic Ah, this may have something to do with the fact that before, the table the chat server uses (friends) was just plain fields, there were no restrictions placed on it whatsoever, so this couldn't happen. 

That explains why it's been crashing so much since FOSS.

**Comment by l-mbert** [comment]
@DarwinAnim8or I might have narrowed it down to #249 if you'd like to take a look at it.

**Pull request merged**
