### PR TITLE
Qb team credit

### PR DESCRIPTION
**Pull request by aronwk-aaron**
When a QB is done when someone is on a team, given every member mission/achievement credit for doing so

### CODE REVIEW

**Comment by EmosewaMC** [comment]
What kind of testing have you done?

**Comment by aronwk-aaron** [comment]
Tested that it works for one player by themself, tested that it works two players on a team

**Review by EmosewaMC — APPROVED** [review]

**Comment by Wincent01** [comment]
Are you sure this is live accurate?

**Comment by EmosewaMC** [comment]
> Are you sure this is live accurate?

100%.  Confirmed with live packet captures that a _team_ would get credit for a build completion, but only the _builder_ would get the loot drops.  Can show you the packets I used to deduce this later if needed.

**Review by Wincent01 — APPROVED** [review]

**Pull request merged**
