### PR TITLE
chore: Convert AMFSerialize to use bitstream references

### PR DESCRIPTION
**Pull request by jadebenn**
Part of raw pointer reduction

### CODE REVIEW

**Comment by EmosewaMC** [comment]
How has this been tested?

**Comment by jadebenn** [comment]
Will be running in-game tests tomorrow per https://github.com/DarkflameUniverse/DarkflameServer/pull/1467#issuecomment-1962846480

**Review by aronwk-aaron — APPROVED** [review]

**Comment by EmosewaMC** [comment]
Make sure you try to open the menu to travel to starbase and back to test this one, its not used in early game

**Review by EmosewaMC — APPROVED** [review]

**Comment by jadebenn** [comment]
Merge pending test of Starbase 3001 functionality

**Comment by jadebenn** [comment]
portabello sure do be portabello-ing

**Pull request merged**
