### PR TITLE
perf: Add path height correction on world load

### PR DESCRIPTION
**Pull request by EmosewaMC**
Because many waypoints for movement place the Y at some height far below the map, we need to correct this height to match that of the navmesh. Doing this at runtime is very expensive as some maps are very tall and so the halfExtents would need to be very large. Doing this at world load is a far more ideal place to take care of this as this only really needs to be done once so that at runtime, more approximate heights can be calculated with the same halfExtents as currently.

Tested that there are no changes aside from the height being changed at world startup.  This may resolve issues with some AI being unable to find a close waypoint on the navmesh due to their waypoint height being far too low for the halfExtents to allow finding of the nearest poly.

### CODE REVIEW

**Review by aronwk-aaron — DISMISSED** [review]
lgtm

**Comment by EmosewaMC** [comment]
I am seeing more successful queries when using a X and Z halfExtents of zero.  about 5% more successful queries from before.

**Comment by EmosewaMC** [comment]
This is resulting in 100% successful queries now.

**Comment by EmosewaMC** [comment]
ran around quite a bit in gnarled forest, crux prime, return to venture explorer and saw no issues with enemies teleporting.

**Comment by EmosewaMC** [comment]
The poly height always matching the one from rhe nearest reg is further reinforced by the lookup now being directly vertical with so variance in the x or z axis.  This ensures you find the correct height or find nothing

**Comment by EmosewaMC** [comment]
Re-tested without capturing the res return from getPolyHeight and actually returning the correct value and no changes except from the expected path fixes.

**Review by aronwk-aaron — APPROVED** [review]

**Review by DarwinAnim8or — DISMISSED** [review]

**Review by Wincent01 — DISMISSED** [review]

**Review by aronwk-aaron — DISMISSED** [review]

**Review by aronwk-aaron — APPROVED** [review]

**Review by DarwinAnim8or — APPROVED** [review]

**Pull request merged**
