### PR TITLE
chore: Change LDFFormat to use BitStream references

### PR DESCRIPTION
**Pull request by jadebenn**
reduction of raw pointers

### CODE REVIEW

**Comment by EmosewaMC** [comment]
How has this been tested?

**Comment by jadebenn** [comment]
@EmosewaMC Ran unit tests, per usual. If you'd like to wait on an in game run before approving, I'll do that on the various branches tomorrow where I try to hit the affected features to make sure everything looks right in-game.

**Comment by EmosewaMC** [comment]
Please test them in-game.  I wont be approving code that hasn't been run in-game to check that it works.

**Comment by jadebenn** [comment]
Combined all the bitstream reference branches into one local branch and ran the game for about an hour where I went from AG to NS to GF following the main questline. Seems stable to me.

**Review by aronwk-aaron — APPROVED** [review]

**Review by EmosewaMC — APPROVED** [review]

**Pull request merged**
