### PR TITLE
add stun immunity script

### PR DESCRIPTION
**Pull request by aronwk-aaron**
several summons use this script to be immune to stuns

### CODE REVIEW

**Comment by aronwk-aaron** [comment]
Valliant/faction summons (owls, spiderling, thwok, bulper, make-shift buddy, etc)
And yes

**Comment by EmosewaMC** [comment]
> Valliant/faction summons (owls, spiderling, thwok, bulper, make-shift buddy, etc) And yes

Did you answer a way with yes lol

**Comment by aronwk-aaron** [comment]
> Did you answer a how with yes lol
went, spawned them, before changes, the could get stunned, same after changes, observed they don't get stunned

**Review by EmosewaMC — APPROVED** [review]
Lgtm

**Review by Wincent01 — APPROVED** [review]

**Pull request merged**
