### PR TITLE
Revert "Remove ability for gmlevel 0 to use /playanim"

### PR DESCRIPTION
**Pull request by Jettford**
Reverts DarkflameUniverse/DarkflameServer#391

I believe this was merged too early and without review from 4 of the requested reviewers.

### CODE REVIEW

**Comment by Jettford** [comment]
@averysumner

**Comment by averysumner** [comment]
Like I stated, this was unintended behavior and wasn’t a feature in live. You can create a PR for a toggle or an extra command if you’d like.

**Comment by Jettford** [comment]
After being contacted by Avery, I was told that there is no proper process for reviewing pull requests after even requesting reviews and was also told that he as a maintainer made a decision to merge it regardless of the reviews left on the PR due to the lack of a requirement for pull request review..

**Comment by averysumner** [comment]
> After being contacted by Avery, I was told that there is no proper process for reviewing pull requests after even requesting reviews and was also told that he as a maintainer made a decision to merge it regardless of the reviews left on the PR due to the lack of a requirement for pull request review..

We're a smaller open source project, us maintainers don't get paid to work on this. I initially requested review on the original PR as a way to gather opinions on the change. If you look at other pull requests, you can see the "request review" feature being used in a similarly relaxed manner. At the time I merged it, the PR was quite stale and still only had comments from two people who I "requested review" from. Having talked it over with the other maintainers, it was decided that I was allowed to merge it, along with leaving a comment about how changes to include a toggle or separate command could be reviewed separately. This is a ten line change in an open source project that I and others maintain in our spare time, there's no reason to get so worked up about this. If you don't like this change, you are free to revert it on your own fork, that's the beauty of open source software.

**Comment by Jettford** [comment]
I am not getting worked up I just think that this is a loss for people that use this software to play with their friends that may not know how to program, this takes away creativity found by the community early on. While yes the goal of this project is obviously live accuracy there is no reason to take away peoples creativity and something that brings a small amount joy and adds a bit of personality to the game. There are solutions to problems without just nuking what is causing problems. I know that from votes held between large quantities of the communities I have been in there were large pushes for this change to not be made. I can reduce the harm this causes to my portions of the community however this just hurts the people that are using standard DLU; the people that you made this for. I don't want to fight over this, I just wish there was more thought before taking something away when there were more solutions mainly ones that were suggested during the review process that was ignored.

**Comment by averysumner** [comment]
> I am not getting worked up I just think that this is a loss for people that use this software to play with their friends that may not know how to program, this takes away creativity found by the community early on. While yes the goal of this project is obviously live accuracy there is no reason to take away peoples creativity and something that brings a small amount joy and adds a bit of personality to the game. There are solutions to problems without just nuking what is causing problems. I know that from votes held between large quantities of the communities I have been in there were large pushes for this change to not be made. I can reduce the harm this causes to my portions of the community however this just hurts the people that are using standard DLU; the people that you made this for. I don't want to fight over this, I just wish there was more thought before taking something away when there were more solutions mainly ones that were suggested during the review process that was ignored.

You are free to make a pull request to add a toggle for this feature if you believe it will detract from user experience, I made that clear in my initial statement alongside the merge.

**Pull request closed without merging**
