### PR TITLE
Added Log content additions

### PR DESCRIPTION
**Pull request by cooltrain7**
- Replaced incorrect/debug cout and printf statements with correct logger -> Log calls that don't break the console flow
- Added extra zone and instance information into a range of world specific ambiguous log calls

Logs with extra info
- Added zone and instance info in dServer connection and lost connection
- Added zone and instance info on finished loading, and shutdown complete

#### Old console logs during shutdown
OldLogs
#### New console logs during shutdown
NewLogs

### CODE REVIEW

**Comment by MickVermeulen** [comment]
Can you resolve the merge conflicts first?

**Comment by cooltrain7** [comment]
> Can you resolve the merge conflicts first?

Yep should be good.

**Review by MickVermeulen — APPROVED** [review]
LGTM. @DarwinAnim8or or @averysumner, any thoughts?

**Comment by MickVermeulen** [comment]
Btw @cooltrain7, sorry for my late response but it seems like another merge request popped up in the meantime, would you mind fixing that?

**Comment by cooltrain7** [comment]
> Btw @cooltrain7, sorry for my late response but it seems like another merge request popped up in the meantime, would you mind fixing that?

@MickVermeulen  No rush, people on holiday and such.

**Pull request merged**
