### PR TITLE
Add zone 1700 to list of accessible zones

### PR DESCRIPTION
**Pull request by enteryournamehere**
This removes the need to use the `force` flag when `/testmap`-ing to that zone.
I've also fixed the indentation in this function (so instead of a mix of spaces and tabs it's just spaces).

### CODE REVIEW

**Comment by DarwinAnim8or** [comment]
The DLU style guide says to use tabs, not spaces.

**Review by DarwinAnim8or — CHANGES_REQUESTED** [review]
Please convert spaces to tabs

**Comment by enteryournamehere** [comment]
Sure, though the only style guide I could find is the [.clang-format](https://github.com/DarkflameUniverse/DarkflameServer/blob/main/.clang-format#L23) file, which specifies that 4 spaces should be used for indentation - for tabs it should have `IndentWidth: 8` and `UseTab: Always` (or `ForIndentation`).

**Comment by averysumner** [comment]
As far as I was aware we were using spaces…

**Comment by KurtStineAI2** [comment]
tabs should be just 4 spaces

**Comment by luxaritas** [comment]
Usage of tabs is specified [in the CONTRIBUTING file](https://github.com/DarkflameUniverse/DarkflameServer/blob/0db954fa72a76b2640dfebcd7987ac3e2ebe0a46/CONTRIBUTING.md#general). Presumably that conflicts with the `.clang-format`

**Comment by averysumner** [comment]
Can you also add 1500 to this?

**Comment by EmosewaMC** [comment]
@averysumner Would it also be a good idea to add comments that say what each zone in the function is?  Or is that defined elsewhere in the files?

**Comment by enteryournamehere** [comment]
> Can you also add 1500 to this?

Sure, done

**Comment by DarwinAnim8or** [comment]
> > Can you also add 1500 to this?
> 
> Sure, done

1500 and 98 are not accessible zones and should not be in this list.
1500 is old starbase, technically present in the pk files but not in the versions list. (new starbase is 1600)
98 is Game Challenge, a leftover entry in the cdclient database that DLU used to insert frostburgh.

**Comment by Xiphoseer** [comment]
Triage: @enteryournamehere Can you address
> 1500 and 98 are not accessible zones and should not be in this list.

Given the name of the PR, it seems like that's the best way forward

**Comment by enteryournamehere** [comment]
> Triage: @enteryournamehere Can you address
> 
> > 1500 and 98 are not accessible zones and should not be in this list.
> 
> Given the name of the PR, it seems like that's the best way forward

Okay, reverted that again... if you guys now agree on using tabs for indentation (I see CONTRIBUTING.md was changed to mention that after the initial comment) I believe this should be good now.

**Pull request merged**
