### PR TITLE
Fix: Falling from Spider Cave now smashes you

### LINKED ISSUE #1282: BUG: Death plane in Advent Gardens spider cave does not function
### Make sure you've done the following:

- [X] I have checked that this issue has not already been reported.

- [X] I have validated that this issue is not a syntax error of either MySQL or SQLite.

- [X] I have pulled the latest version of the main branch of DarkflameServer and have confirmed that the issue exists there.

### DarkflameServer Version

411dce7

### Issue Description

The death plane in the Advent Gardens spider cave does not smash your character (despite the console stating it sends a die request).

### Reproduction Steps

1. Go to the Advent Gardens spider cave
2. Succumb to the pressures of life and jump off the edge

https://github.com/DarkflameUniverse/DarkflameServer/assets/9892985/73ddfbb3-3e00-4535-9a9c-50b3c0decbc2

### Expected Behavior

Death.

### Environment

Windows client, WSL Ubuntu server

### PR DESCRIPTION
**Pull request by jadebenn**
Fixes #1282. Tested by jumping off the cliff repeatedly.

### CODE REVIEW

**Review by EmosewaMC — COMMENTED** [review]
Can you check deaths in other scenarios?  Racing, enemies and various others as well?  This GM is sent in more than 1 scenario so its good to check bounds

**Comment by jadebenn** [comment]
Not sure how to enter the racing instances with one player... Is there an easier way to test besides logging in with two accounts?

**Comment by EmosewaMC** [comment]
> Not sure how to enter the racing instances with one player... Is there an easier way to test besides logging in with two accounts?

worldconfig.ini

**Comment by jadebenn** [comment]
Death in racing works as expected.

**Comment by jadebenn** [comment]
"Smash me" works as well

**Review by EmosewaMC — APPROVED** [review]

**Review by aronwk-aaron — APPROVED** [review]

**Pull request merged**
