### PR TITLE
Remove Friend Fix

### LINKED ISSUE #267: BUG: Remove friend doesn't remove friend
### Make sure you've done the following:

- [X] I have checked that this issue has not already been reported.

- [X] I have validated that this issue is not a syntax error of either MySQL or SQLite.

- [X] I have pulled the latest version of the main branch of DarkflameServer and have confirmed that the issue exists there.

### Issue Description

Using remove friend does nothing. No friend is removed or any changes to the database.

### Reproduction steps

- Get a friend or use a second account
- Add them as a friend
- Try to remove them

### Expected Behavior

The "friend" is removed.

### Environment

WSL 1 - Ubu 20.04

### PR DESCRIPTION
**Pull request by EmosewaMC**
Fixes #267 
The function for remove friend is working as intended, however I noticed that the function was not properly getting the LWOOBJID for one of the queries, and as such was unable to perform the necessary work to properly remove a friend.

First, the character name that was being fetched from the packet was using the incorrect offset and was changed to be the proper offset to get the name correctly. Then the conversion to a LWOOBJID was corrected from ClearBit to SetBit to get the correct ID for querying the table. I have also cleaned up the function a bit to reduce unnecessary work.

I have tested this in my personal instance and this does remove multiple friends from the client, database and the friends client.

### CODE REVIEW

**Comment by Xiphoseer** [comment]
This might conflict with #311

**Comment by EmosewaMC** [comment]
> This might conflict with #311

Looks like it does however, the lines it conflicts with can be safely overwritten.  The lines they are changing are simply info for querying the database.  Will test their changes on my end to make sure there are no conflicts @Xiphoseer

**Comment by EmosewaMC** [comment]
when #311 is merged I will update this PR with the proper changes.

**Comment by EmosewaMC** [comment]
@Xiphoseer since #311 has been put to the side for now could we get this one merged?  If needed I can test again to confirm this works but it should still be functional without issues

**Pull request closed without merging**
