### PR TITLE
Implement lower cap datagram / MTU size

### PR DESCRIPTION
**Pull request by EmosewaMC**
LEGO Universe uses a lower datagram / MTU size so we are also going to use this.  May also address other issues, we'll see.

Tested that the server compiles and boots.  

Will test that I can login with a substantially sized Create Character packet in the morning

### CODE REVIEW

**Review by aronwk-aaron — APPROVED** [review]

**Comment by aronwk-aaron** [comment]
Only questions is, Should this be set on all servers and not just world server?
Would make sense if that was the case, but just want to ask the stupid question incase no one has thought of it

**Comment by EmosewaMC** [comment]
> Only questions is, Should this be set on all servers and not just world server? Would make sense if that was the case, but just want to ask the stupid question incase no one has thought of it

This is being done in dServer.  All dServers will have their MTU size set to this value, not just World

**Comment by aronwk-aaron** [comment]
ty, i'm blind

**Comment by Wincent01** [comment]
As with the rate limiter, a precompiler value with a default would be ideal imo.

**Review by Jettford — APPROVED** [review]

**Comment by EmosewaMC** [comment]
> As with the rate limiter, a precompiler value with a default would be ideal imo.

Will do in a future pr.  I created #896 for that.

**Pull request merged**
