### PR TITLE
Re-made Loot.h include <vector> to allow for the server to build on GCP

### PR DESCRIPTION
**Pull request by saltshaker**
Commit 0531365 made the server not build on GCP due to removing `#include <vector>` from Loot.h. This just re-adds it.

### CODE REVIEW

**Comment by HailStorm32** [comment]
Can confirm. Made the following changes after pulling to get it to compile

**Comment by averysumner** [comment]
What environment is "GCP"?

**Comment by saltshaker** [comment]
Google cloud platform, so it's Debian 10.

**Comment by averysumner** [comment]
I'm on Debian Buster compiling on GCC and I have no issues. Are you using clang?

**Comment by saltshaker** [comment]
No I'm using GCC as well. I don't believe clang is installed on my machine.

**Comment by Wincent01** [comment]
This PR does more than add back the include statement. Closing; open a new one with only the intended changes. Don't want a bypass of the chat filter in the history.

**Pull request closed without merging**
