### PR TITLE
Moonbase fix

### PR DESCRIPTION
**Pull request by Jettford**
Gravity in Moonbase was broken at some point during the development of DLU and I don't think that it used to work the way I have just fixed it, can anyone think of any other solutions to the problem?

### CODE REVIEW

**Comment by MichaelFedora** [comment]
This is pretty curious -- why doesn't OnEnter fire alongside OnCreate when a play enters a world by default?

**Comment by Jettford** [comment]
I think it might have happened when the physics engine was changed.

**Comment by Jettford** [comment]
I will take a longer look at this now tbh

**Comment by averysumner** [comment]
It previously worked by just sending the physics effect client sided.

**Review by DarwinAnim8or — CHANGES_REQUESTED** [review]
While this is a solution to the problem, it is not elegant to do collision checks like this in a Component.

I'd much rather fix dPhysics so OnEnter gets fired upon creation inside of a trigger than do this. I'll take a look tomorrow, so no worries ;)

**Comment by Jettford** [comment]
Alright I have taken a further look at dPhysics and I think I may be wrong about the root issue here, I am not really sure what the issue is, the TriggerEvent for OnEnter should be fired every tick as long as they are collided unless I missed something.

**Comment by Jettford** [comment]
```
[10-12-21 20:46:58] [PhantomPhysicsComponent]: Processing events on new objects, x amount: 11
[10-12-21 20:46:58] [PhantomPhysicsComponent]: Character hit: 5652
[10-12-21 20:46:58] [PhantomPhysicsComponent]: Processing events on new objects, x amount: 11
[10-12-21 20:46:58] [PhantomPhysicsComponent]: Character hit: 5652
[10-12-21 20:46:58] [PhantomPhysicsComponent]: Processing events on new objects, x amount: 11
[10-12-21 20:46:58] [PhantomPhysicsComponent]: Character hit: 5652
```
Alright I know that the character is colliding with it and that `TriggerEvent("OnEnter", <character>)` is being called so I am not really certain where the issue is here

**Comment by Jettford** [comment]
Simply constructing the trigger if its target is itself solves the issue.

@DarwinAnim8or if you could review

**Review by DarwinAnim8or — APPROVED** [review]

**Pull request merged**
