### PR TITLE
fix: MultiZoneEntranceComponent selection windows opening for everyone in the zone

### LINKED ISSUE #1194: BUG: Buccaneer Monkey inflicts damage on the player
### Make sure you've done the following:

- [X] I have checked that this issue has not already been reported.

- [X] I have validated that this issue is not a syntax error of either MySQL or SQLite.

- [X] I have pulled the latest version of the main branch of DarkflameServer and have confirmed that the issue exists there.

### DarkflameServer Version

2e386d2

### Issue Description

.

### Reproduction Steps

- Equip 7416
- Throw the monkey at an enemy (slot 4)
- stand near the monkey until it explodes
- observe that you took 5 damage

### Expected Behavior

this should not happen

### Environment

Ubuntu Server 20.04

### LINKED ISSUE #1195: BUG: LUP Rocket interface opens for other players in the instance
### Make sure you've done the following:

- [X] I have checked that this issue has not already been reported.

- [X] I have validated that this issue is not a syntax error of either MySQL or SQLite.

- [X] I have pulled the latest version of the main branch of DarkflameServer and have confirmed that the issue exists there.

### DarkflameServer Version

2e386d2

### Issue Description

When accessing the rocket launcher in Starbase 3001, the interface for choosing the LUP worlds opens for you, but also opens for other players in the instance.

### Reproduction Steps

- Go to the rocket pad in Starbase 3001
- With another player present, interact with it (or have the other player interact)
- observe as everyone gets the popup

### Expected Behavior

this should not happen

### Environment

Ubuntu Server 20.04

### PR DESCRIPTION
**Pull request by aronwk-aaron**
fixes #1195
Tested that the menu still works

### CODE REVIEW

**Comment by EmosewaMC** [comment]
This has been tested yes?

**Review by EmosewaMC — APPROVED** [review]

**Comment by MustacheMan2** [comment]
I think you meant to have mentioned #1195

**Comment by EmosewaMC** [comment]
> I think you meant to have mentioned #1195

yes

**Review by DarwinAnim8or — APPROVED** [review]
lgtm

**Pull request merged**
