### PR TITLE
Add GitHub Actions Workflow

### PR DESCRIPTION
**Pull request by Xiphoseer**
This PR adds a github actions workflow for a Linux build as well as a `CMakePresets.json` that is defined by cmake and required by the action ([lukka/run-cmake](https://github.com/lukka/run-cmake)) that is used.

The `CMakePresets.json` file sets `jobs` i.e. the `-j` flag to `2` by default. That corresponds to the hardware as described in https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources and cuts the build time in half (about 8 minutes instead of 15).

Warnings end errors are scraped from the log and displayed inline in the GitHub web UI. See <https://github.com/Xiphoseer/DarkflameServer/pull/2/files> for an example. The warnings there are caused by adding `-Wextra`. This may be a good opportunity to tweak the warning settings a bit more to get more feedback on our own code but using different settings for 3rd party code.

At the end of a build, a zip file is uploaded as an artifact, which a maintainer can use to publish a release.

### CODE REVIEW

**Comment by Xiphoseer** [comment]
CC #228

**Comment by averysumner** [comment]
Is there a possibility to add a Windows build to this with either clang or MSVC++?

**Comment by Xiphoseer** [comment]
> Is there a possibility to add a Windows build to this with either clang or MSVC++?

Yeah, there are windows runners too, afaik the only difference is that every minute counts twice in terms of billing (10x for Mac). We need some way to install dependencies there and someone needs to write the actions yaml. I would suggest to only do windows builds on main though and not PRs.

**Comment by TheNoim** [comment]
I like it. Later I could combine this with #90 and auto build docker images :)

**Comment by averysumner** [comment]
> Yeah, there are windows runners too -- afaik the only difference is that every minute counts twice in terms of billing (10x for Mac). We need some way to install dependencies there and someone needs to write the actions yaml. I would suggest to only do windows builds on main though and not PRs.

Do we have a limited amount of minutes? I'm not entirely sure how Actions works... I know we ran out of artifact storage back when we used Actions on our private repository.

**Comment by Xiphoseer** [comment]
> Do we have a limited amount of minutes? I'm not entirely sure how Actions works... I know we ran out of artifact storage back when we used Actions on our private repository.

According to <https://github.com/pricing> minutes should be free for public repos, but there are some limits for concurrent jobs, queues and artifacts as specified in <https://docs.github.com/en/actions/learn-github-actions/usage-limits-billing-and-administration#usage-limits>

**Comment by averysumner** [comment]
I'm cool with merging this and having the possibility of adding a Windows build to it later.

**Review by averysumner — APPROVED** [review]

**Pull request merged**
