### PR TITLE
Implemented script for exploding dummy in Nexus Tower Combat Training

### LINKED ISSUE #264: BUG: Sentinel Combat Challenge Red Target Dummy takes no damage
### Make sure you've done the following:

- [X] I have checked that this issue has not already been reported.

- [X] I have validated that this issue is not a syntax error of either MySQL or SQLite.

- [X] I have pulled the latest version of the main branch of DarkflameServer and have confirmed that the issue exists there.

### Issue Description

In the sentinel combat challenge, you can only get to a little over 100 points because the red target dummy (which, when taking damage, damages other players), does not receive any damage. This makes a couple achievements unachievable.

### Reproduction steps

- Play the Sentinel Combat Challenge in Nexus Tower
- Get up to a little over 100 points to start getting the Red Target Dummies
- Get stuck because you cannot destroy it

### Expected Behavior

That you should be able to destroy the red target dummy.

### Environment

Window client / ubuntu server

### PR DESCRIPTION
**Pull request by EmosewaMC**
Fixes #264 
Implements the script that is attached to the exploding dummy in Nexus Tower Combat Training.  Pretty much a copy paste of the original Combat Dummy script, but with the added behaviors and the self smash after 1 hit.  

Tested on local ubuntu instance.  Other dummies act normal.  Red exploding dummies now correctly explode, and do their respective AOE attack as well as spawn the next dummy when they die.

### CODE REVIEW

**Review by Jettford — APPROVED** [review]

**Comment by metric-ambient** [comment]
When testing this PR on my google cloud instance, the red dummy is destroyed but the next dummy still does not spawn.

**Comment by EmosewaMC** [comment]
> When testing this PR on my google cloud instance, the red dummy is destroyed but the next dummy still does not spawn.

Sounds like you didnt configure the patch correctly then.  Dummy spawns correctly on my end and this code would not change between types of servers

**Comment by EmosewaMC** [comment]
> When testing this PR on my google cloud instance, the red dummy is destroyed but the next dummy still does not spawn.

fixed

**Comment by metric-ambient** [comment]
> > When testing this PR on my google cloud instance, the red dummy is destroyed but the next dummy still does not spawn.
> 
> Sounds like you didnt configure the patch correctly then. Dummy spawns correctly on my end and this code would not change between types of servers

Not sure how I could have misconfigured the patch, as I'm using github CLI running gh pr checkout 445 to switch to a new branch to test it out. All other PRs have worked properly using this method. Would like to hear if others have experienced this issue or if I'm alone in it.

**Comment by EmosewaMC** [comment]
@metric-ambient there issue is now fixed

**Comment by EmosewaMC** [comment]
Not sure who to ping for this one but this PR should be good to go.  The exploding dummy now correctly dies after being hit once, explodes and spawns the next one

**Pull request merged**
