### PR TITLE
Updated Mail Commands

### PR DESCRIPTION
**Pull request by Verathian2**
- Added 3 new mail commands:
1. setmailsub: Similar to setanntitle with an announcement, this sets the subject of the next mail sent via mailitem or mailitemall.
2. setmailbody: Similar to setannmsg with an announcement, this sets the body of the next mail sent via mailitem or mailitemall.
3. mailitemall: Sends a mail to all characters created on the server (online and offline)
- Added "Help" messages to mail commands when the command is given no arguments.
- Altered the "mail sent" message to be more descriptive when mail is successfully sent.

### CODE REVIEW

**Review by DarwinAnim8or — CHANGES_REQUESTED** [review]
Some things of note here, but the main one I have issue with is the "mailItemAll" command you created. Getting *all* created characters and then looping through them to do an insert + outputting to chat will be very slow. 

Also, to mimick live more, it should only give out the item to people who are currently online, for mythran events + then you don't need to hammer the MySQL database with possibly thousands of queries. 

### The other, smaller issues:

1. Please use `u"your text here"` for string constants, rather than GeneralUtils::ASCIIToUTF16. Strings have a large performance impact and you should use them, and converting strings, as little as possible. 
2. Following the above, use a stringstream to build sentences. Using + "" involved a lot of implicit string copying, which is slow, stringstreams were designed for this in mind and are faster!
3. Line 949 and 955 both use "GetMailSubject", one should be Body
4. Please do not chain if / else statements together. Leave one line of whitespace after closing an else
5. Please do not break up lines like below:
`ChatPackets::SendSystemMessage(
			sysAddr,
			GeneralUtils::ASCIIToUTF16("Sending item to " + playerName + " with subject '" + entity->GetCharacter()->GetMailSubject()
				+ "' and body '" + entity->GetCharacter()->GetMailBody() + "'.")
		);`


I know this sounds like a lot but I do appreciate any effort people put into this! The fact you wrote code for an open source project like this is great :) 

Only reason I wrote so much here is because I know C++ is a language that has lots of quirks and other languages are totally fine with some things that in C++ are *working*; but not the ideal solution. So if you're new I hope you can learn from it!

**Comment by Verathian2** [comment]
Hey Darwin!

Thank you for all the feedback! I will definitely put it to good use in making the code a bit more efficient. Having only really dug into the code the last couple of days, I still have a lot to learn, and appreciate all the feedback!

**mailitemall**
- That sounds good to me! The primary reason I didn't do it for just online players is that the activity table doesn't always seem to track when a player logs off (activity = 1). I often found that activity = 0 (which I presume means online) was sometimes set on characters that I know aren't online. Perhaps this is a bug I will pursue a fix for soon!
- Another reason I was thinking of keeping this one in was that I wanted to mail the beta tester book to all characters on my server as a way to thank them for dealing with the technical difficulties we've faced in the first month of it being online. Perhaps this command could be kept with a lag warning, and a "mailitemallonline" could be created for the GM events some may wish to do? :) I'm fine either way, just let me know what you think! I could always write my own insert to run when the server is "in maintenance" for my next DLU update.

**Other Smaller Issues**
Thank you for all the notes! I'll make some changes, retest, and get another commit in so you can review and make sure the formatting is up to the DLU standard.

Thank you,
Verathian

**Comment by Verathian2** [comment]
Hi Darwin,

I have updated the code reflecting your feedback. I also slightly modified the mail subject and body defaulting, as well as the way they are inserted into the insert query. I also updated mailitemall to only mail players with a max activity value of 0. The activity table as I mentioned before seems to have some offline characters in an online status, but that's a bridge we'll cross in another issue!

**Comment by Verathian2** [comment]
Hello,

I have added one more, very minor adjustment to this request. While not related, it was so minor that I didn't want to create a whole new pull request. This update adjusts the stun time when you are "exiting" a paradox portal in NT. Previously the stun duration kept me standing there for multiple seconds after the animation ended. The adjusted time now lets me move when the animation is over.

**Comment by Verathian2** [comment]
Adjusted the assembly portal as well, which also stunned the player for an excessive amount of time.

**Comment by averysumner** [comment]
> Adjusted the assembly portal as well, which also stunned the player for an excessive amount of time.

Please put changes like this in different PRs.

**Review by DarwinAnim8or — CHANGES_REQUESTED** [review]
Sorry for the delay in this, been busy.

I see the Nt Teleport scripts had a constant modified from 4 to 2, but not in the PlayAnimation call. Could you correct this? 
Also, where did you get the correct animation time from? CDClient?

**Comment by Verathian** [comment]
Hey @DarwinAnim8or , I have actually made quite a few updates to this and run tests on my server (for the mail functions). I am going to close this PR and open a new one, as I've changed my process for coding PRs a fair amount in the last week.

As for the portal update, I have opened https://github.com/DarkflameUniverse/DarkflameServer/pull/289 which contains only these changes (per Avery's request). The animation time of 2 seconds was something I simply tested using trial and error, as the script `l_nt_assemblytube_client.lua` does not contain any timing on the client side, and a paradox portal script does not exist in the same file location. Therefore, I believe that this stun timing is only scripted on the client side.

I first tried 3 seconds, but found I was still stuck for a second (both for the assembly tubes and the paradox portals) after using them. I then reduced the time to 2 seconds, and I was able to move instantly as the animation ended. I modified these variables about 2 weeks ago on my server, and I've only heard good things about the change.

**Pull request closed without merging**
