### PR TITLE
fix: bump connector version

### PR DESCRIPTION
**Pull request by Xiphoseer**
Update MariaDB Connector library to fix 0-padding issue with newer mariadb servers.

(Turns out the "old" way of detecting `is_mariadb` in connector-c was brittle and has since been removed)

### CODE REVIEW

**Comment by EmosewaMC** [comment]
Looks like the problematic file is updated on a local.  great find!

**Review by EmosewaMC — APPROVED** [review]

**Review by Jettford — APPROVED** [review]
Approved without testing.

**Review by DarwinAnim8or — APPROVED** [review]
lgtm

**Comment by DarwinAnim8or** [comment]
good job team

**Pull request merged**
