### PR TITLE
fix: Dismantling of models taking many many more resources than necessary

### PR DESCRIPTION
**Pull request by EmosewaMC**
allows the user to only send a maximum of numUniqueBricksInModel gms to their client when dismantling a model instead of numBricksInModel * numModelsToDismantle gms.  The difference here is literally sending 30ish gms at the most vs 1.5 million.

Tested that the client doesn't crash due to dismantling so many models

### CODE REVIEW

**Review by aronwk-aaron — APPROVED** [review]
packets go brrrrr

**Review by Jettford — APPROVED** [review]

**Comment by MustacheMan2** [comment]
_I_ am finding that this fix has made crashes _more_ frequent

**Comment by EmosewaMC** [comment]
Are you just going to say its more frequent or are you going to say what is causing it as well?

**Comment by EmosewaMC** [comment]
if you are talking about getting kicked to login, please ensure UGCUSE3DSERVICES is set to 7:0 and that your game is in a folder called client.

**Comment by EmosewaMC** [comment]
I have found an item with the issue.  I would appreciate just being given the item that has an issue rather than a vague hint that there are issues still as it doesnt happen with most models.

**Comment by MustacheMan2** [comment]
Sorry about my previous comment, I knew at the time that my comment wasn't especially helpful and I still posted it for some reason, I just couldn't be bothered to provide evidence. The issue I'm having is also a server crash, not a client crash, so I'm just going to quietly walk away lol

**Comment by EmosewaMC** [comment]
regardless its fixed now, please confirm the fix on your end if possible

**Pull request merged**
