### PR TITLE
Uncommented and repaired fix for quickbuilds

### PR DESCRIPTION
**Pull request by Jettford**

### CODE REVIEW

**Comment by averysumner** [comment]
I mean I guess this "fixes" it...

**Comment by Wincent01** [comment]
If I recall correctly this had a tendency to make things worse at times.

**Comment by averysumner** [comment]
> If I recall correctly this had a tendency to make things worse at times.

Yeah there’s probably a reason it was commented out…

**Comment by Jettford** [comment]
> If I recall correctly this had a tendency to make things worse at times.

From what I was told it was only bad if it happened while building.

**Pull request merged**
