### PR TITLE
Fully Implemented Shooting Gallery Mission and Achievement Fixes

### LINKED ISSUE #143: Can't get achievements in Cannon Cove Shooting Gallery
You cannot complete the missions or achievements regarding cumulative points in CCSG
You cannot get the achievements for hits in a row in CCSG
Basically, all the achievements besides score are unobtainable

### LINKED ISSUE #303: BUG: Paradox Daily 75.000 Point Gnarled Forest Minigame Mission doesn't complete
### Make sure you've done the following:

- [X] I have checked that this issue has not already been reported.

- [X] I have validated that this issue is not a syntax error of either MySQL or SQLite.

- [X] I have pulled the latest version of the main branch of DarkflameServer and have confirmed that the issue exists there.

### Issue Description

Cog Blammo's daily mission of achieving a score of 75.000 in the shooting gallery doesn't show up as finished, cannot receive rewards from him.
Rejoining the game worsens the situation, as the progress resets and doesn't track anymore.

grafik
_Progress meter after rejoin_

### Reproduction steps

1. Pick up the daily quest series from Paradox vendor Cog Blammo on the nimbus plaza
2. Reach the part where you have to achieve a score of 75.000 points in the gnarled forest shooting gallery
3. Reach 75.000 points or more
4. Return to Cog Blammo
5. _Quest shows up as complete in the quest tracker at the top of the screen, but not in Cog Blammo's dialogue_
6. Restart game
7. _Score resets_
8. Click on Cog Blammo's dialogue for the same quest again
9. Play the minigame again
10. _Mission progress now doesn't track anymore and is uncompletable (?!?)_

### Expected Behavior

Quest always tracks correctly and shows up as completed in Cog Blammos UI

### Environment

Ubuntu

### PR DESCRIPTION
**Pull request by EmosewaMC**
Fully implemented all shooting gallery achievements and missions.  Maximum current streak is now kept track of properly as before it was always set to twelve.  I have tested all achievements to be properly working and various daily missions to confirm they were progressing properly.  
Fixes #303 
Fixes #143

### CODE REVIEW

**Comment by cooltrain7** [comment]
> Maximum current streak is now kept track of properly as before it was always set to twelve.

Though it still doesn't reset when you miss. This makes everything _massively_ easier and I think it should be a requirement before `Crack Shot` is added.

**Comment by EmosewaMC** [comment]
> > Maximum current streak is now kept track of properly as before it was always set to twelve.
> 
> Though it still doesn't reset when you miss. This makes everything _massively_ easier and I think it should be a requirement before `Crack Shot` is added.

The only time the streak should reset is when you miss without a super charged cannon or hit a friendly ship without a supercharged cannon.  I will add misses for no supercharge cannon resetting the streak

**Comment by cooltrain7** [comment]
> Edit: There is currently no logic to track cannon shots or misses. The streak achievements are hard enough as is and so I believe its fine to put cannot shooting and missing logic into a future PR and just get these merged asap so people can get to doing these missions

Yep thats correct the SG/leaderboards were actaully one of the first things I looked at working on. The way the shooting is currently done is a little diffrent from how the lua has it, with it making use of `onShootingGalleryFire` and `onActivityNotify` the latter being the one you would want to implement.

Then again I can see why you would want to keep the PR more focused.

**Comment by EmosewaMC** [comment]
The client sided lua files are different from the server sided ones and I don't believe can be interchanged.  Apologies if I am wrong though.

**Comment by Jettford** [comment]
Yeah client and server lua files are completely different

**Pull request merged**
