### PR TITLE
feat: lock players behind free-to-play gating and make server better

### PR DESCRIPTION
**Pull request by aronwk-aaron**
This is to help foster support and funding for the project, by making those who can't code be restricted to AG only.

<details>
  <summary>Details</summary>
<details>
  <summary>Details</summary>
<details>
  <summary>Details</summary>
<details>
  <summary>Details</summary>
<details>
  <summary>Details</summary>
<details>
  <summary>Details</summary>
<details>
  <summary>Details</summary>
<details>
  <summary>Details</summary>
<details>
  <summary>Details</summary>
<details>
  <summary>Details</summary>

  ```
  This is a joke, don't merge this.
  ```
</details>
</details>
</details>
</details>
</details>
</details>
</details>
</details>
</details>
</details>

### CODE REVIEW

**Review by EmosewaMC — DISMISSED** [review]
Finally we can start making some $

**Review by DarwinAnim8or — APPROVED** [review]
lgtm! lets get that bread bois

**Comment by Wincent01** [comment]
capitalism go brrrrrr

**Review by Wincent01 — DISMISSED** [review]

**Review by Jettford — DISMISSED** [review]
finally, LGTM!

**Comment by jadebenn** [comment]
lgtm. glad we're finally getting around to this.

**Review by jadebenn — APPROVED** [review]

**Comment by aronwk-aaron** [comment]
Sorry, this is has pushed me beyond my *bricking* limit. 
384855 line changes? we've discussed, this.... the limit for one PR is 372918 line changes, which should be generous enough. I can't believe that you would put this many changes in one PR, who do you expect to review this is we are above the agreed upon limit. I'm disappointed in you for pushing beyond this limit YOU put in place, Emo. Very hypocritical
Closing.

<details>
  <summary>Details</summary>
<details>
  <summary>Details</summary>
<details>
  <summary>Details</summary>
<details>
  <summary>Details</summary>
<details>
  <summary>Details</summary>
<details>
  <summary>Details</summary>
<details>
  <summary>Details</summary>
<details>
  <summary>Details</summary>
<details>
  <summary>Details</summary>
<details>
  <summary>Details</summary>

  ```
 This was fun lmao, good job
  ```
</details>
</details>
</details>
</details>
</details>
</details>
</details>
</details>
</details>
</details>

**Comment by DarwinAnim8or** [comment]
And so the spirit of capitalism was driven away for another day

**Pull request closed without merging**
