### PR TITLE
Added UNIQUE to charInfo table for names

### LINKED ISSUE #321: ENH: Add UNIQUE constraint to `charinfo.name` database column
### Is your feature request related to a problem?

It looks like the `charinfo.name` database column currently has no `UNIQUE` constraint:
https://github.com/DarkflameUniverse/DarkflameServer/blob/0a7d9c46eba551b5e2f908caf9c689f4139bffb4/migrations/dlu/0_initial.sql#L18

But uniqueness seems to be enforced in the code here:
https://github.com/DarkflameUniverse/DarkflameServer/blob/0a7d9c46eba551b5e2f908caf9c689f4139bffb4/dGame/UserManager.cpp#L263-L266

### Describe the solution you'd like

Would it make sense to add a `UNIQUE` constraint, or is there something I am overlooking?

### Repository breaking implications

_No response_

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by EmosewaMC**
Added UNIQUE for charInfo table for names.  Tested creating characters with the same name and had no issues.  Fixes #321 suggestion

### CODE REVIEW

**Comment by cooltrain7** [comment]
I wonder if it would be a good idea to add a DB template check during startup to validate each of the tables/columns/constraints and update them accordingly (or at a minimum log that changes are needed). Otherwise you're relying on people to spot commits that effect the DB and apply them. Not just for this commit but for others in the future that will add new columns.

**Comment by Xiphoseer** [comment]
Yeah, technically, this should be a new migration file `1_unique_charinfo_names.sql` (or similar) with
```sql
ALTER TABLE charinfo ADD UNIQUE (name); 
```

**Comment by EmosewaMC** [comment]
> Yeah, technically, this should be a new migration file `1_unique_charinfo_names.sql` (or similar) with
> 
> ```sql
> ALTER TABLE charinfo ADD UNIQUE (name); 
> ```

Gotcha.  Will update the PR (and the README?) to reflect this change.

**Comment by Jettford** [comment]
> I wonder if it would be a good idea to add a DB template check during startup to validate each of the tables/columns/constraints and update them accordingly (or at a minimum log that changes are needed). Otherwise you're relying on people to spot commits that effect the DB and apply them. Not just for this commit but for others in the future that will add new columns.

@cooltrain7 Maybe instead of a schema checker maybe there should be a migration runner added to the server, so instead of checking the schema just run migrations that aren't listed as merged in a new table.

**Comment by Marcono1234** [comment]
Thanks a lot @EmosewaMC for addressing the issue I raised!

In case you are not aware of it, GitHub supports certain [keywords for pull requests](https://docs.github.com/en/github/writing-on-github/working-with-advanced-formatting/using-keywords-in-issues-and-pull-requests). This way GitHub automatically links pull request and issue, and closes the issue when the pull request is merged (maintainers can also manually add the link if necessary). It should also be possible to edit the description of your pull request retroactively and add the line "Resolves #321" to it.

**Pull request merged**
