### PR TITLE
Add note for compiling with multiple jobs

### PR DESCRIPTION
**Pull request by EmosewaMC**
Tested that appending -j4 compiles with 4 jobs at once.

### CODE REVIEW

**Comment by aronwk-aaron** [comment]
want to add to the packages to install `libssl-dev zlib1g zlib1g-dev` for linux as well?

**Comment by EmosewaMC** [comment]
> want to add to the packages to install `libssl-dev zlib1g zlib1g-dev` for linux as well?

Those are already listed?

**Comment by EmosewaMC** [comment]
Screen Shot 2023-01-17 at 4 22 17 AM
`zlib1g-dev` is just a more updated version of `zlib` so im more inclined to support that over the standard package unless of course other systems just don't have it, then we can probably add it

**Comment by aronwk-aaron** [comment]
Ah, so not only can users not read, I cannot read!

**Review by aronwk-aaron — APPROVED** [review]

**Review by Wincent01 — APPROVED** [review]

**Pull request merged**
