### PR TITLE
Add GitHub CodeQL code scanning workflow

### LINKED ISSUE #318: ENH: Add GitHub code scanning workflow
### Is your feature request related to a problem?

It might be useful to use [GitHub code scanning](https://docs.github.com/en/code-security/code-scanning/automatically-scanning-your-code-for-vulnerabilities-and-errors/about-code-scanning) to detect potential vulnerabilities and errors in the code.

### Describe the solution you'd like

Add a workflow for running CodeQL on the repository. The necessary steps are described [here in the documentation](https://docs.github.com/en/code-security/code-scanning/automatically-scanning-your-code-for-vulnerabilities-and-errors/setting-up-code-scanning-for-a-repository#setting-up-code-scanning-using-actions). The only necessary change to the action template added by these steps is to specify `submodules: true` for the "Checkout repository" workflow step. With that code scanning works successfully (tested on fork):

Code scanning findings screenshot

However, it does not seem to use the `CMakePresets.json` introduced by #248. If that is an issue, it might be possible to modify the workflow to as described [here](https://docs.github.com/en/code-security/code-scanning/automatically-scanning-your-code-for-vulnerabilities-and-errors/configuring-the-codeql-workflow-for-compiled-languages#adding-build-steps-for-a-compiled-language) to provide a different build command (maybe `cmake --preset CMakePresets.json`? I am not very familiar with CMake).

One issue is that this also scans the third-party code, which increases the time code scanning takes. Though, this could also be seen as advantage, because it flags potential issues in the third-party code.
Maybe the workflow should therefore be restricted to only run on pushes to `main`, only run on a schedule, or only run when certain files are changed by pull requests, as described [here](https://docs.github.com/en/code-security/code-scanning/automatically-scanning-your-code-for-vulnerabilities-and-errors/configuring-code-scanning#avoiding-unnecessary-scans-of-pull-requests). Excluding the third-party code from code scanning might not be easily possible with the CodeQL code scanning action; or it would require custom build commands.

Additionally, or alternatively, other code scanning actions such as [Microsoft C++ Code Analysis](https://devblogs.microsoft.com/cppblog/microsoft-cpp-code-analysis-with-github-actions/) could be used as well.

### Repository breaking implications

_No response_

### Describe alternatives you've considered

Not add any automatic code scanning. After all it is just a "nice to have" addition.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Marcono1234**
Resolves #318

Adds a GitHub code scanning workflow using CodeQL. The workflow is currently configured to run the [`security-and-quality` query suite](https://docs.github.com/en/code-security/code-scanning/automatically-scanning-your-code-for-vulnerabilities-and-errors/configuring-code-scanning#using-queries-in-ql-packs). That suite contains additional security, maintainability and reliability queries, whereas by default only certain security queries would be run.

The workflow first builds the thirdparty libraries (and therefore excludes them from analysis) and afterwards compiles the sources of this project. This is necessary because currently the CodeQL action [does not support exclusions for compiled languages](https://docs.github.com/en/code-security/code-scanning/automatically-scanning-your-code-for-vulnerabilities-and-errors/configuring-code-scanning#specifying-directories-to-scan) (maybe there is a cleaner way to perform this with CMake; suggestions are welcome).
Alternatively the workflow could also be changed to analyze the third party libraries as well; the results for them can then be [filtered in the security view](https://docs.github.com/en/code-security/code-scanning/automatically-scanning-your-code-for-vulnerabilities-and-errors/managing-code-scanning-alerts-for-your-repository#filtering-code-scanning-alerts). That also yields a couple additional findings for the code of this project for creation of `RakNet::RakString`, being reported as [Non-constant format string](https://codeql.github.com/codeql-query-help/cpp/cpp-non-constant-format/). I am not sure if those are legit; if so then the `RakString` constructor with `char *format, ...` as parameters might be rather unreliable.

I am not very familiar with GitHub code scanning yet either, so any feedback is appreciated!

### CODE REVIEW

**Comment by averysumner** [comment]
Is this really needed?

**Comment by EmosewaMC** [comment]
> Is this really needed?

@Xiphoseer Is this what you had in mind for the codeQL stuff?

**Comment by codeshaunted** [comment]
Can you explain what utility this provides?

**Comment by Marcono1234** [comment]
It scans the code on push and pull request events for potential vulnerabilities and bug patterns, and is well integrated into GitHub.
For example [in this line](https://github.com/DarkflameUniverse/DarkflameServer/blob/a7744e8a9a4db033dba0798147e25b47709d4a16/dGame/dGameMessages/GameMessages.cpp#L5341-L5341) it detected that the variable is not initialized. Or [in this line](https://github.com/DarkflameUniverse/DarkflameServer/blob/445c01d485f577a4b51e208e88c402585c1763b6/dZoneManager/Level.h#L37) it noticed a missing `return`.
This can be seen when you click on the [details of the workflow run](https://github.com/DarkflameUniverse/DarkflameServer/pull/453/checks?check_run_id=5157087942). For newly changed code which introduces bugs or vulnerabilities this will also be displayed [within the changed code](https://docs.github.com/en/code-security/code-scanning/automatically-scanning-your-code-for-vulnerabilities-and-errors/triaging-code-scanning-alerts-in-pull-requests), and you can also configure what severity will cause the GitHub workflow run to fail. Additionally, as maintainer you can see [all the alerts for the repository](https://docs.github.com/en/code-security/code-scanning/automatically-scanning-your-code-for-vulnerabilities-and-errors/managing-code-scanning-alerts-for-your-repository) and can filter them, for example by branch name or severity.

It is certainly no silver bullet because it likely has both false negatives and false positives, but it hopefully helps to make the code more secure and reliable.

**Comment by Jettford** [comment]
Closing this because it flags too many non-errors and all of the actual issues are simply ones in features we don't use in 3rd party libraries.

**Comment by Marcono1234** [comment]
> Closing this because it flags too many non-errors

You don't have to address all errors and warnings and can sort or dismiss them in the GitHub UI, though I can understand that the number of reported findings is a bit overwhelming, and for sure not all of them are that relevant or are false positives. If you want I can adjust it to only use the default security queries, it then only has two findings (or `security-extended`, has 13 findings):
- One "Comparison of narrow type with wide type in loop condition", and I think that might be a true positive:
https://github.com/DarkflameUniverse/DarkflameServer/blob/ef8c2a40f384973c68c5cc483b2e602e9579fb4f/dZoneManager/Zone.cpp#L429
- One "Multiplication result converted to larger type" in `NiPoint3.cpp` which can probably be ignored

> in features we don't use in 3rd party libraries

I thought I had solved that by first building the 3rd party libraries independently from the code scanning. Can you point out a finding which is in unused 3rd party code?

Thanks for considering it nonetheless! In case you want to revisit this, please let me know.

**Pull request closed without merging**
