### PR TITLE
fix: Make multi-config presets work again

### PR DESCRIPTION
**Pull request by jadebenn**
Reverted breaking change for multiple-configuration presets that was previously included in #1669

### CODE REVIEW

**Comment by jadebenn** [comment]
On further review, I'm not sure #1669 should have been merged at all.

**Comment by Jettford** [comment]
I believe this PR is counter-productive to changes I am trying to make on the origin/windows-clang branch. Not closing as I am awaiting further feedback.

**Review by Xiphoseer — APPROVED** [review]

**Comment by Xiphoseer** [comment]
Fwiw: I'm generally in favor of not tying things down to a `build` directory, because it doesn't even have to be called that in cmake.

At the same time, this is our own env var which shouldn't confuse tooling too much, so if it restores stuff that was working it may be fine to merge even if replaced by a better way later.

**Comment by EmosewaMC** [comment]
This makes it so CI no longer contains ini files.  I would rather prioritize CI and release over development environments.

**Comment by jadebenn** [comment]
closing - there is a better approach

**Pull request closed without merging**
