### PR TITLE
chore: Reduce manual cmake include directories

### PR DESCRIPTION
**Pull request by jadebenn**
Testing a way to remove most of the CMake directory include statements. Right now I have it compiling with only the thirdparty directories listed manually in the main cmake file

### CODE REVIEW

**Comment by jadebenn** [comment]
Please let me know what you all think about this approach versus our current one.

**Review by EmosewaMC — CHANGES_REQUESTED** [review]
headers do not need to be in sources as they are not compiled.

**Comment by EmosewaMC** [comment]
> Please let me know what you all think about this approach versus our current one.

This approach was already being done in #1387 and that pr is nearly finished just missing some final touches for mac builds

**Comment by jadebenn** [comment]
They are different approaches, and my approach does require the headers to be in the libraries.

**Comment by jadebenn** [comment]
Closed after further discussion. There is a reason that #1387 is doing things the way it does.

**Pull request closed without merging**
