### PR TITLE
WSL Readme Section Changes

### PR DESCRIPTION
**Pull request by PyEddy**
As the title says, this will be changing some stuff in the readme section for WSL

Changes include 

- Added the Windows 11 RTM build 22000 to the WSL requirement for Windows 11 `WSL requires...`
- Added "Change WSL version" which is optional if the user wants to use WSL1 instead
- Added a note that lets users reading the readme know about the network issues that may occur when using WSL and that its not an issue to do with DLU

I think this PR is a good idea especially knowing some people use WSL and report network issues sometimes that DLU can't solve as its to do with Microsoft

### CODE REVIEW

**Comment by Jettford** [comment]
> Please note that Microsoft sometimes ends up breaking WSL (there tends to be network issues when using WSL) and DLU won't be able to fix them so verify that its not WSL that is broken before reporting an issue.

This is very non-descript and unhelpful to the average user. Please note the actual issue to do with WSL 2 and recommend use of WSL 1.

**Comment by aronwk-aaron** [comment]
Honestly, if you're on windows, do native windows compiling. WSL is really just a dev tool to begin with, and if you're a dev you'll know how to save to not use it. It should not be used for long running play servers

**Comment by PyEddy** [comment]
> > Please note that Microsoft sometimes ends up breaking WSL (there tends to be network issues when using WSL) and DLU won't be able to fix them so verify that its not WSL that is broken before reporting an issue.
> 
> This is very non-descript and unhelpful to the average user. Please note the actual issue to do with WSL 2 and recommend use of WSL 1.

Right will change the note to specify that WSL2 is having issues and add a recommendation for WSL1

**Comment by EmosewaMC** [comment]
The only change out of that list that I think is worth noting is the recommending that users use WSL1 over WSL2 for stability.  The other changes I don't believe will provide much more clarity than is already there

**Comment by PyEddy** [comment]
> The only change out of that list that I think is worth noting is the recommending that users use WSL1 over WSL2 for stability.  The other changes I don't believe will provide much more clarity than is already there

I mean if we are recommending WSL1 we will have to show them how to change WSL versions as I have done

I think everything is great imo but I can change things if you want

**Comment by aronwk-aaron** [comment]
No reason that we should be telling users to downgrade to wsl1, wsl2 works fine, the issues with it are out of are control. as well as MSFT has stabilized wsl2 over the previous months.
Additionally, a windows setup guide has been made by a community member, and people should be using native windows instead of WSL (be it 1 or 2)

**Pull request closed without merging**
