### PR TITLE
Update CMake minimum requirement

### LINKED ISSUE #308: BUILD: Requires at least CMake 3.14
### Make sure you've done the following:

- [X] I have read the [installation guide](https://github.com/DarkflameUniverse/DarkflameServer/blob/main/README.md).

### Platform

Ubuntu

### Architecture

x86

### Error Logs

`FetchContent_MakeAvailable` is from CMake 3.14: https://cmake.org/cmake/help/latest/module/FetchContent.html#command:fetchcontent_makeavailable

```
CMake Error at CMakeLists.txt:78 (FetchContent_MakeAvailable):
  Unknown CMake command "FetchContent_MakeAvailable".


-- Configuring incomplete, errors occurred!
```

### PR DESCRIPTION
**Pull request by ThexXTURBOXx**
Fixes #308

### CODE REVIEW

**Comment by Marcono1234** [comment]
Might also be necessary to adjust the README (it currently says "cmake must be version 3.12 or higher") and `CMakePresets.json`.

**Comment by ThexXTURBOXx** [comment]
Thank you very much, searched for (hopefully) all occurences now!

**Comment by johntor** [comment]
Why this update is necessary? Which features of the new version are needed to build the project?
Because a new minor version of a tool/library is out does not mean we should all be pushed to update!
Except if just want to show that you are active to project and creating meaningless pull requests!

**Comment by ThexXTURBOXx** [comment]
@Johntor Before accusing me of creating "meaningless" PRs, please read the mentioned issue accordingly.

**Comment by johntor** [comment]
> Johntor Before accusing me of creating "meaningless" PRs, please read the mentioned issue accordingly.

I'm sorry! You are right! That is why I deleted my post.

**Pull request merged**
