### PR TITLE
Log some recvfrom errors on linux

### PR DESCRIPTION
**Pull request by Xiphoseer**

### CODE REVIEW

**Review by aronwk-aaron — APPROVED** [review]

**Comment by EmosewaMC** [comment]
Ideally this should be tested at least for functionality before merging just to ensure the code does what we expect it to do.

**Comment by aronwk-aaron** [comment]
I can see about spinning this up on a server in my homelab and letting it run for a week to see if the issue happens and hits this code, unless there is a way that we could manually recreate the issue

**Comment by Xiphoseer** [comment]
I thought about just adding two binaries with RakPeers, let them do some sort of ping roundtrip and then run it once with a forced exit and once with a crash, that should test a lot of the relevant code paths.

We could also send an empty udp packet by hand and see what happens, maybe.

**Review by Wincent01 — APPROVED** [review]

**Comment by EmosewaMC** [comment]
Let's keep an eye on this for the next couple weeks.  If there aren't any issues past that then we should be all fine.

**Pull request merged**
