### PR TITLE
:smiley:

### PR DESCRIPTION
**Pull request by Jettford**

### CODE REVIEW

**Comment by NinjaOfLU** [comment]
Tysm! This was getting annoying!

**Comment by EmosewaMC** [comment]
lol

**Review by EmosewaMC — CHANGES_REQUESTED** [review]
Approved

**Comment by Terrev** [comment]
doesnt work

**Comment by Jettford** [comment]
> doesnt work

works on my machine, try docker

**Comment by Terrev** [comment]
> > doesnt work
> 
> works on my machine, try docker

works better but doesnt at all now

**Comment by Jettford** [comment]
closing, political bias.

**Pull request closed without merging**
