### PR TITLE
Make changes to allow Windows to run under a debug environment 

### PR DESCRIPTION
**Pull request by Jettford**
- Replace all interaction of std::string and sqlString.

### CODE REVIEW

**Review by EmosewaMC — APPROVED** [review]
Looks fine to me.  Are there more of these in the codebase?  If there are more we may want to change them as well in the future just to be consistent and not have this issue pop-up in the future.

**Comment by aronwk-aaron** [comment]
> Looks good to me. Are there more of these in the codebase? If there are more we may want to consider changing them as well in the future just to be consistent and not have this issue pop-up in the future.

I did a bried overview and there are still some in some distance corners of the code base that use std::string.
I can take a look at updating them and adding to this PR if wanted

**Comment by Jettford** [comment]
There definitely are more but these seem to be the only ones causing issues. This is some definite black magic bugginess.

**Review by aronwk-aaron — APPROVED** [review]
since this is only a debug issue and does not effect release, I'll go ahead an approve it. If other places cause issues, we can just update them later

**Pull request merged**
