### PR TITLE
feat: Update kill credit to give credit to first person to deal health damage.

### LINKED ISSUE #230: BUG: kill stealing is inaccurate to live
### 

- [X] I have checked that this issue has not already been reported.

- [X] I have validated that this issue is not a syntax error of either MySQL or SQLite.

- [X] I have pulled the latest version of the main branch of DarkflameServer and have confirmed that the issue exists there.

### Issue Description

Currently, the person to deal a killing blow on an enemy gets the loot - this is how it worked earlier in LU's lifespan, but they later changed it:

In live, the first person to land a blow on an enemy's health bar would get the loot

The "health bar" part is important; armor didn't count

The result was, in scenarios where multiple people (or teams) were fighting an ape, or dragon on crux, everyone would be smacking away at the armor, but as that got close to 0, the best strategy was to build your engineer turrets, activate your rapid-fire abilities - anything to increase you/your team's chances of being the first to land a hit on the enemy's actual health

Then when health got to 0 and the enemy died, you'd wait in anticipation to see if loot dropped for you/your team, or if the little particles would appear around other minifigures to indicate they'd gotten the powerups + loot (side note: something's up with the effects that play from picking up health/armor/imagination in DLU, but I haven't had the chance to figure out exactly what yet)

Dumb? Yeah

Buuuut at least it prevented people from kill stealing normal enemies without armor bars lol

### Reproduction steps

click frantically until purple thing dies

### Expected Behavior

first hit on a health bar claims its loot

### Environment

The Cloud

### PR DESCRIPTION
**Pull request by EmosewaMC**
Fixes #230 
Only give kill credit to the first person to deal life damage to an enemy.  Tested the following scenarios:
- Player A and Player B not on a team:
    - Player A gets the first hit on a spider and Player B kills the spider.  Player A got credit.
    - The same but for Player B.
- Player A and Player B on a team and a third Player C not on the team:
    - Player A and Player B got team credit for a kill when either of them hit a spider first and Player C got credit for the kill when they hit the spider first.
    - Player A and Player B got the dragon credit when they were the first to deal health damage to the dragon (not armor damage).
    - Player C got dragon kill credit when they were the first to deal health damage to the dragon.  
    - If an AI reset their health back to full, a new first damager was now possible, overriding the original.

### CODE REVIEW

**Review by aronwk-aaron — APPROVED** [review]
The true menace returns

**Comment by Wincent01** [comment]
What happens when a player smacks a dragon, leaves, maybe even leaves the world, what that Dragon then be useless?

Even if this is live accurate, I don't think it should be forced, because it's poor design.

**Comment by EmosewaMC** [comment]
I imagine in live however, they forsaw players doing that, so they likely had checks to make sure the player actually remained in combat for the fight to prevent people from grieving like that

**Comment by aronwk-aaron** [comment]
Do enemies maintain an agro list? could it be as simple as checking if they are still in that agro list.

Also just for my own sake as to why this PR hasn't been fully approved.

1. Handle players leaving combat
2. Add option for maintaining DLU's current behavior (Default to live behavior)

**Comment by EmosewaMC** [comment]
Closing as this is not a feature I want to implement, nor does it entice me to fix this.  Someone else can resolve it or I will pick it up when I feel like fixing it.

**Comment by jadebenn** [comment]
Both options kind of suck, honestly. I think "first hit" is marginally fairer, but not by much.

**Pull request closed without merging**
