### PR TITLE
Fix three-part names coming across as INVALID with custom client path

### PR DESCRIPTION
**Pull request by luxaritas**
This is due to AssetManager not being used, so the character names were being pulled from build/res, which may not exist.

Tested by running the server with a custom client path and creating a character, which successfully set the three-part name instead of setting it as INVALID

This is split out from #834 as it is a distinct bug fix critical for servers with a custom client path

### CODE REVIEW

**Comment by EmosewaMC** [comment]
Could you also test that chat whitelist works too please?

**Comment by luxaritas** [comment]
Yep, works as expected

**Comment by luxaritas** [comment]
Also please confirm that GetFIleAsBuffer and then converting to an istream is the correct approach here vs just constructing the paths as they were before but using `Game::assetManager->GetResPath()`

**Review by EmosewaMC — CHANGES_REQUESTED** [review]
Yes you are correct, however I believe bounds checking similar to how we do it [here](https://github.com/DarkflameUniverse/DarkflameServer/blob/b17ba56af17f42f47dafdfbe56913caabf49c450/dZoneManager/Zone.cpp#L46) so if the file cannot be loaded for some reason, an error is logged and the server is unable to start.  This would also allow a very traceable error for if an issue happens with those files!

**Comment by luxaritas** [comment]
Confirmed that if a relevant file is not available, the message is logged and the server raises an exception

**Review by EmosewaMC — APPROVED** [review]
Thanks for this!

**Review by Wincent01 — APPROVED** [review]

**Pull request merged**
