### PR TITLE
simplify  path fixing for packed vs unpacked

### PR DESCRIPTION
**Pull request by aronwk-aaron**
fix slashes for hasfile for unpacked client checking

Tested with unpacked client on linux
Tested with packed on linux

### CODE REVIEW

**Review by Jettford — CHANGES_REQUESTED** [review]
This removes functionality?

**Comment by EmosewaMC** [comment]
> This removes functionality?

He says hes tested with packed and unpacked clients - not sure how anything has changed?

**Comment by Jettford** [comment]
He definitely has not tested enough.

**Review by Jettford — APPROVED** [review]

**Comment by EmosewaMC** [comment]
Has chatting, character create, macros and testmap been tested?

**Review by EmosewaMC — APPROVED** [review]
lgtm

**Comment by aronwk-aaron** [comment]
> Has chatting, character create, macros and testmap been tested?

yes, I did test all three of those, chatting and char create names were already good.
Testmap is the only thing that "HasFile" is used for since we don't care about what's in the file, just that it exists in the first place before we attempt to go to it

**Pull request merged**
