### PR TITLE
Fix NPC Proxy items

### PR DESCRIPTION
**Pull request by EmosewaMC**
NPCs are supposed to equip the sub items of items they equip and were not doing so.  This PR adds this functionality and fixes and issue where Neido on Crux Prime was not wearing their sword.

Tested that Neido has their sword and that other NPCs that wear proxies also get their proxies equipped.  Had no issues with any other world crashing.

### CODE REVIEW

**Comment by NealSpellman** [comment]
Why is this on the racinglaptimefix branch and including that commit?

**Comment by aronwk-aaron** [comment]
> Why is this on the racinglaptimefix branch and including that commit?

git moment lol

**Comment by EmosewaMC** [comment]
> Why is this on the racinglaptimefix branch and including that commit?

Because I didn't switch branches?  Does this really matter that much?

**Review by aronwk-aaron — APPROVED** [review]
LGTM

**Pull request merged**
