### PR TITLE
feat: Leaderboards

### LINKED ISSUE #471: BUG: Racing doesn't update leaderboards (missing code)
### Make sure you've done the following:

- [X] I have checked that this issue has not already been reported.

- [X] I have validated that this issue is not a syntax error of either MySQL or SQLite.

- [X] I have pulled the latest version of the main branch of DarkflameServer and have confirmed that the issue exists there.

### Problem: 
Racing doesn't update leaderboards

### Solution/root of problem:
From my look into the code, it looks like the code for updating the leaderboards is not implemented in the racing code.
https://github.com/DarkflameUniverse/DarkflameServer/blob/ad52facef71e1349057512237ccbd0b157af19f9/dGame/dComponents/RacingControlComponent.cpp#L860

Looking at other minigames with functioning leaderboards, they all call `StopActivity` 
https://github.com/DarkflameUniverse/DarkflameServer/blob/02bf5937dc2b22cad2d0e2e330c928235fd72c13/dScripts/BaseSurvivalServer.cpp#L380

which in turn calls `SaveScore`. 
https://github.com/DarkflameUniverse/DarkflameServer/blob/0531365cb55d8954c240b8f0096ece0d1fe6bf1e/dScripts/ActivityManager.cpp#L76

I can't seem to find anything similar to that in the racing code.

### Reproduction steps

1. Complete a race on any track
2. Notice score doesn't get pushed to leaderboard

### Expected Behavior

Leaderboards should be updated when a race is finished

### Environment

Google Cloud 
Debian 11

### LINKED ISSUE #633: BUG: Friends leaderboards don't display the correct items
### Make sure you've done the following:

- [X] I have checked that this issue has not already been reported.

- [X] I have validated that this issue is not a syntax error of either MySQL or SQLite.

- [X] I have pulled the latest version of the main branch of DarkflameServer and have confirmed that the issue exists there.

### DarkflameServer Version

all

### Issue Description

title

### Reproduction Steps

1) place on a leaderboard
2) observe that the friends leaderboard either shows multiple of you or nothing

### Expected Behavior

a correct leaderboard filtering out non-friends

### Environment

all

### PR DESCRIPTION
**Pull request by EmosewaMC**
- Fix leaderboards not displaying the correct entries
- Fix leaderboards not displaying any score even though the data was sorted correctly
- Implement the following leaderboards
  - Racing
  - Nexus Jawbox
  - Unused Leaderboard 4 (idk either but its in the client)
- Finish implementing the Shooting Gallery leaderboard
- Provide a much cleaner and harder to mis-use API
- Clearer scoring system and variable names

Final todo list:
- [x] Weekly filter
- [x] throttled???
- [x] classic vs dlu survival scoring

Fixes #471 
Fixes #633

### CODE REVIEW

**Comment by aronwk-aaron** [comment]
@EmosewaMC would throttled be if they click to much/fast between scoreboards, they get API rate limited?

**Comment by EmosewaMC** [comment]
The following tests have been performed
- Load the following leaderboards and all sub-leaderboards
  - Racing
  - Survival
  - SurvivalNS
  - ShootingGallery
  - MonumentRace
  - Footrate
- Tested the following cases that give a better score record the new score
  - DLU survival scoring updates the saved score if the score is better
  - live survival scoring updates the saved score if the time is better
  - racing prioritizes best overall time and then best lap time.  Wins is updated idempotent of a better score or not.
  - MonumentRace prioritizes lower score
  - Footrace prioritized higher score
  - Shooting gallery prioritizes score, then streak and finally hit percentage
  - Battle of Nimbus station has a special case since one of the values is ranked high -> low and the other is ranked low -> high.  Still functions normally.

**Review by aronwk-aaron — DISMISSED** [review]

**Comment by EmosewaMC** [comment]
retested all the following leaderboards and scores were saved for the initial save
footrace
monumentrace
agsurvival
racing
shooting gallery
Bons

Will now test for repeat scores

**Comment by EmosewaMC** [comment]
tested that scores properly update when they are beaten as well

**Comment by EmosewaMC** [comment]
classic_survival_scoring also works as expected

**Comment by EmosewaMC** [comment]
all leaderboards are showing ranks in the correct order, with the correct rankings, and first 5 and bottom 5 show the top 10 or bottom 10 respectively

**Review by aronwk-aaron — COMMENTED** [review]
awesome

**Review by aronwk-aaron — APPROVED** [review]

**Review by DarwinAnim8or — APPROVED** [review]

**Pull request merged**
