### PR TITLE
BoNS Time Smash Fix

### PR DESCRIPTION
**Pull request by Verathian**
"Time Smash" achievements are being triggered one wave too soon (the moment you complete the wave before the boss). This fix adjusts it to be the proper wave that contains the boss.

### CODE REVIEW

**Review by MickVermeulen — APPROVED** [review]
LGTM, can you confirm that you've tested this for a full BONS run?

**Comment by Verathian** [comment]
I can confirm I've tested it up to Whack Bliddo (the 2nd to last boss), and the time smashes are now triggering the moment you kill the boss. I didn't test the riders, but I know from playing with a group of friends on my server that they were triggering a wave early as well, so I bumped them back (since they spawn and die on wave 29). It seems like they were all just accidentally set to the wave before the boss actually spawned.

**Comment by MickVermeulen** [comment]
Alright, would you mind trying this for a full run? Just flying around with a jetpack and doom hammer to smash everything is already good, just want to know the end-game doesn't get messed up accidentally.

**Comment by EmosewaMC** [comment]
@MickVermeulen This is ready to merge

**Comment by Saymoan** [comment]
@MickVermeulen I just did a run through of BoNS with this change applied and I can confirm that nothing breaks from it

**Comment by MickVermeulen** [comment]
Thank you guys! Merging.

**Pull request merged**
