### PR TITLE
fix: remove pending callback timers logic

### LINKED ISSUE #1426: BUG: Stromling Mech not attacking in avant gardens survival
### Make sure you've done the following:

- [X] I have checked that this issue has not already been reported.

- [X] I have validated that this issue is not a syntax error of either MySQL or SQLite.

- [X] I have pulled the latest version of the main branch of DarkflameServer and have confirmed that the issue exists there.

### DarkflameServer Version

Latest

### Issue Description

Stromling Mech aren't attacking player when nearby in survival minigame.

### Reproduction Steps

Join survival minigame in Avant Gardens.

### Expected Behavior

Stromg Mech should attack player.

### Environment

Ubuntu

### PR DESCRIPTION
**Pull request by EmosewaMC**
tested that mechs now work in avant gardens survival
fixes #1426

### CODE REVIEW

**Comment by Xiphoseer** [comment]
Doesn't this introduce the same issue with possibly changing the size of callbackTimers while the for loop on it is active?

**Comment by EmosewaMC** [comment]
> Doesn't this introduce the same issue with possibly changing the size of callbackTimers while the for loop on it is active?

yes and it doesnt matter it uses a reference into the container.  It is fine.

**Comment by EmosewaMC** [comment]
the code clearly shows `auto& callbackTimer = m_CallbackTimers[timerPosition];` which is fully safe given the condition for continuing the loop is if the size is < than size.

**Comment by Xiphoseer** [comment]
> the code for the update loop uses references to elements in the timer container as `auto& callbackTimer = m_CallbackTimers[timerPosition];` which is fully safe given the condition for continuing the loop is if the index is < than size.
> 

Safe, yes. What I mean is the size() getting called as the loop condition which may change within the loop (causing infinite cycles)

**Comment by EmosewaMC** [comment]
> > the code for the update loop uses references to elements in the timer container as `auto& callbackTimer = m_CallbackTimers[timerPosition];` which is fully safe given the condition for continuing the loop is if the index is < than size.
> 
> Safe, yes. What I mean is the size() getting called as the loop condition which may change within the loop (causing infinite cycles)

Ok then I will change back to the broken version which does not iterate over timers correctly.

**Comment by EmosewaMC** [comment]
isolated the actual root cause.  will push a different pr soon.

**Pull request closed without merging**
