### PR TITLE
remove memory leaks in hydrant scripts

### PR DESCRIPTION
**Pull request by aronwk-aaron**
i am plumber, i fix leaks

### CODE REVIEW

**Review by Wincent01 — APPROVED** [review]
"Remove" makes this fault sound  all intentional :P

**Comment by aronwk-aaron** [comment]
> "Remove" makes this fault sound all intentional :P

more like me not knowing what I'm doing lol

**Review by EmosewaMC — COMMENTED** [review]
I'm confused, won't this cause undefined behavior in entity settings is this ldf data is accessed?

**Comment by aronwk-aaron** [comment]
Leaks were else where

**Pull request closed without merging**
