### PR TITLE
Added joined a faction flag

### PR DESCRIPTION
**Pull request by EmosewaMC**
Added logic to set the player flag for joining a faction as was done in live.  Tested on Ubuntu and had zero issues.

### CODE REVIEW

**Comment by Jettford** [comment]
Is this in the packet captures?

**Review by Jettford — APPROVED** [review]

**Comment by averysumner** [comment]
I was the one who translated this script from Lua and I feel like I would've added that if it was there... It's possible I missed it. Do you have any proof it was there?

**Comment by averysumner** [comment]
Found the script, I thought it was going to be in 02_server but it wasn't: https://explorer.lu-dev.net/scripts/ai/ns/l_ns_get_faction_mission_server.lua

I don't see this flag getting set, but I also don't see these faction flags getting manually set, so it's likely I figured out the flags on my own. This is probably fine to merge.

**Comment by Jettford** [comment]
Before this is merged, would it be worth adding a simple check during Player creation on world connect to set this flag if they are in a faction, as a like legacy check?

**Comment by EmosewaMC** [comment]
I was thinking about that Jett.  I think that would be a good thing for retroactive flag setting

**Comment by EmosewaMC** [comment]
@Jettford I added a retroactive flag check to the world server for when the level load is completed by user to set their joined a faction flag to true.  @averysumner if you could double check if this is an ok change here or if I should put this elsewhere that'd be great.

**Comment by Jettford** [comment]
You are putting `== true` after each GetFlag, you don't need to do this, it already returns a bool.

**Comment by EmosewaMC** [comment]
@Jettford Noted for future implementations of booleans in statements.  Implemented that change

**Comment by cooltrain7** [comment]
Might be a good idea to move it to a function? I would add it as a character function `Character::SetRetroactiveFlags` or something of the like,  Keeps it in one place, and creates a place if others need to set missed flags in the future.

**Comment by Jettford** [comment]
I don't really see the need, it will never need to be called from anywhere else and isn't a large amount of code

**Comment by cooltrain7** [comment]
> I don't really see the need, it will never need to be called from anywhere else and isn't a large amount of code

Yea its just and idea, just feels a little odd to have faction flag being set from a spot halfway down WorldServer.

**Comment by Jettford** [comment]
WorldServer is literally one massive function ¯\_(ツ)_/¯

**Comment by DarwinAnim8or** [comment]
> Might be a good idea to move it to a function? I would add it as a character function `Character::SetRetroactiveFlags` or something of the like, Keeps it in one place, and creates a place if others need to set missed flags in the future.
> 
> Oh I also don't know what the sentiment would be to change out magic numbers for use of enums? I.e `flagID = 46;` for `flagID = VENTURE_FACTION;`? Though that could always be another PR that changes it across the board (where applicable).

Please do this instead, HandlePacket shouldn't be responsible for player's save data.

**Comment by EmosewaMC** [comment]
@DarwinAnim8or moved the retroactive flag check to its own function in character.cpp.  Tested and had no issues.

**Comment by EmosewaMC** [comment]
> Oh I also don't know what the sentiment would be to change out magic numbers for use of enums? I.e `flagID = 46;` for `flagID = VENTURE_FACTION;`? Though that could always be another PR that changes it across the board (where applicable).
Separate PR imo

**Pull request merged**
