### PR TITLE
Add ship shake to not log about being missing

### PR DESCRIPTION
**Pull request by Jettford**
This log was causing confusion and issues when in reality there was no problem present.

### CODE REVIEW

**Comment by averysumner** [comment]
Looks good to me.

**Comment by MickVermeulen** [comment]
Not really a fan of this as people will just see invalidscript errors a bit later when going to AG. Either we actually fix the scripts or we just turn off the invalidscript warnings.

**Comment by Jettford** [comment]
I think the main issue of this one is that you see it the second you open the server, later ones people tend to not really care about

**Comment by Jettford** [comment]
Maybe the solution would just be changing the log to make it seem less like an error

**Comment by DarwinAnim8or** [comment]
Hmm, I have my reservations about doing this. It makes sense for this script because it is in fact implemented, but on the logging of invalid scripts should be it's own issue IMO. 

I'd propose that we create a .ini variable to see if we should be logging them, a sort of "verbose logging" mode if you will

**Comment by Jettford** [comment]
Would you like me to do that?

**Comment by Jettford** [comment]
Or was it more of a at some point it should be done?

**Comment by Jettford** [comment]
> Hmm, I have my reservations about doing this. It makes sense for this script because it is in fact implemented, but on the logging of invalid scripts should be it's own issue IMO.
I'd propose that we create a .ini variable to see if we should be logging them, a sort of "verbose logging" mode if you will

@DarwinAnim8or Done the above listed suggestions, take a look at latest commit

**Review by DarwinAnim8or — APPROVED** [review]
Have not tested locally but these changes seem sane

**Comment by Jettford** [comment]
@averysumner @MickVermeulen Could you give this a review? Someone added you as reviewers.

**Comment by MickVermeulen** [comment]
LGTM

**Comment by MickVermeulen** [comment]
I'll merge, given that Avery has already approved and Darwin also approved.

**Pull request merged**
